SELECT 
	*
FROM
	INFORMATION_SCHEMA.TABLES T

	INNER JOIN INFORMATION_SCHEMA.COLUMNS C
	ON
		C.[TABLE_NAME]=T.[TABLE_NAME]

WHERE
	--C.[COLUMN_NAME] LIKE '%ITEMBARCODE%'
	T.[TABLE_NAME] = 'DonorReferral'
/*	
	AND 
	C.[COLUMN_NAME] = 'NETWEIGHT'
*/